package enums;

//phân loại các phế liệu nhựa
public enum PlasticType {
    HDPE,//Can nhựa, chai nước giặt, chai dầu gội, ống nhựa, thùng sơn...
    PET ,//Chai nước khoáng, chai nước giải khát, hộp nhựa thực phẩm trong suốt...
    PVC,//Ống dẫn nước, vỏ dây điện, màng bọc plastic, nhựa ván sàn...
    PP//Hộp đựng thức ăn quay microware, cốc trà sữa, vỏ bình ắc quy, đồ chơi...
}
